{{- if and .Values.rbac.create ( not .Values.rbac.root ) }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: {{ include "kubernetes-dashboard.fullname" . }}
  name: {{ include "kubernetes-dashboard.fullname" . }}

rules:
  # Allow Metrics Scraper to get metrics from the Metrics server
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
{{- end }}