kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    k8s-app: {{ include "kubernetes-dashboard.fullname" . }}
  name: {{ include "kubernetes-dashboard.fullname" . }}
  namespace: {{ .Release.Namespace }}

