{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: {{ include "kubernetes-dashboard.fullname" . }}
  name: {{ include "kubernetes-dashboard.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubernetes-dashboard.fullname" . }}

subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes-dashboard.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}