apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: {{ include "kubernetes-dashboard.fullname" . }}
  name: kubernetes-dashboard-certs
  namespace: {{ .Release.Namespace }}
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: {{ include "kubernetes-dashboard.fullname" . }}
  name: kubernetes-dashboard-csrf
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  csrf: ""

---

apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: {{ include "kubernetes-dashboard.fullname" . }}
  name: kubernetes-dashboard-key-holder
  namespace: {{ .Release.Namespace }}
type: Opaque

