{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubernetes-dashboard.serviceAccountName" . }}
  labels:
    k8s-app: {{ include "kubernetes-dashboard.fullname" . }}
{{ include "kubernetes-dashboard.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
